server:
  port: 9002
spring:
  application:
    name: clk-oauth
  datasource:
    url: jdbc:mysql://localhost:3306/clerk?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml


logging:
     level:
        com.wtf.oauth.mapper: debug
